@hostname = localhost
@port = 8000
@host = {{hostname}}:{{port}}
###

### Login 
# @name authen
POST http://{{host}}/api/admin/login HTTP/1.1
Content-Type: application/json

{
  "email": "sing@dev.com",
  "password": "123456"
}

###
@token = {{authen.response.body.$.token}}

GET http://{{host}}/api/admin/user
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET http://{{host}}/api/admin/ambassador/user
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET http://{{host}}/api/ambassador/products/frontend
Content-Type: application/json