version: '3.9'
services:
  # backend:
  #   build: .
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  #     - redis

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8080

  redis:
    image: redis:latest
    ports:
      - 6379:6379
